name: justitis
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  barcode_widget: ^2.0.3
  flutter:
    sdk: flutter
  flutter_advanced_drawer: ^1.3.4
  flutter_native_splash: ^2.2.19
  google_sign_in: ^6.1.0
  google_sign_in_web: ^0.12.0
  responsive_framework: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ingredienti.json
    - assets/images/home_background.jpg

flutter_native_splash:
  color: "#F5F3F4"
  image: assets/logo.png

